### PR TITLE
add data from jikan api

### PR DESCRIPTION
**Pull request by mfardaniyah**
tolong koreksi data manga dari jikan api yah Win

### CODE REVIEW

**Review by windymega — COMMENTED** [review]
Mbak tolong tambahin detail datanya ya

**Review by windymega — COMMENTED** [review]
minta tolong tambahin data 6-10 yaah

**Comment by ghilman27** [comment]
Hi, nice repo and collaboration here.
Really appreciates the work 👏

You created a merge request which is the best practice for developers to communicate and share their idea on code
You also create separate branches to segregate your work and versions

But it appears Farda didn't contribute a single commit anywhere
Even though I know you two actually separate the work, make sure to include your name and commit in the future, so everyone notices your contribution.

**Comment by ghilman27** [comment]
It also appears you imported `manga.csv` but didn't actually use it in the code
instead of creating an "automated" flow to convert `manga.csv` into `data_fix.csv`, you created a _hardcoded_ variable inside your notebook. like this one

```python
url_conan = "https://api.mangadex.org/manga?title=Detective Conan: Zero’s Tea Time"
url_nightmare = "https://api.mangadex.org/manga?title=The Nightmare Family"
url_bassen = "https://api.mangadex.org/manga?title=Bassen"
url_onepiece = "https://api.mangadex.org/manga?title=One Piece Episode A"
url_zoro = "https://api.mangadex.org/manga?title=One Piece Special - Roronoa Zoro Falls Into the Sea"
url_naruto = "https://api.mangadex.org/manga?title=Naruto"
url_tetsudou = "https://api.mangadex.org/manga?title=Tetsudou Shoujo Manga"
url_xeno = "https://api.mangadex.org/manga?title=Detective Xeno and the Seven Locked Murder Rooms"
url_slam = "https://api.mangadex.org/manga?title=Slam Dunk!"
url_goddess = "https://api.mangadex.org/manga?title=A Goddess Without Inconvenience"
```

instead, you could turn that into this
```python
import pandas as pd

# get url
data = pd.read_csv("/path/to/manga.csv")
data["url"] = [f"https://api.mangadex.org/manga?title={title_en}" for title_en in data['title_en']]

# open the output file in "write" mode
with open("output_file.csv", "w") as file:
  # loop api request for each manga, clean the data, then write it to the file, row by row
  for url in data["url"]:
    response = request.get(url)
    data_json = response.json()
    comma_separated_string_data= convert_data_json_to_comma_separated_string(data_json)
    file.write(f"{comma_separated_string_data}\n")
```

**Pull request merged**
